# Generated by Django 5.2.12 on 2026-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0014_alter_floorplan_label_default'),
        ('properties', '0010_alter_property_property_type_amenitycategory_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='developments', to='properties.amenity', verbose_name='Amenidades (catálogo)'),
        ),
    ]
