# Generated by Django 5.2.12 on 2026-05-07 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_exclusive_advisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno'), ('condominio', 'Condominio'), ('casa_condo', 'Casa en condominio'), ('penthouse', 'Penthouse'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('consultorio', 'Consultorio'), ('bodega', 'Bodega'), ('nave_industrial', 'Nave industrial'), ('rancho', 'Rancho'), ('otro', 'Otro')], default='casa', max_length=20, verbose_name='Tipo de Propiedad'),
        ),
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-grid-1x2', help_text='Ejemplo: bi-shield-check', max_length=40, verbose_name='Icono Bootstrap')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de amenidades',
                'verbose_name_plural': 'Categorías de amenidades',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order'], name='properties__sort_or_4743e4_idx'), models.Index(fields=['slug'], name='properties__slug_e3fa22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre canónico')),
                ('display_name', models.CharField(max_length=120, verbose_name='Nombre visible')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-check2-circle', help_text='Icono minimalista (Bootstrap Icons). Se pinta en verde olivo en UI.', max_length=40, verbose_name='Icono Bootstrap')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('is_premium', models.BooleanField(db_index=True, default=False, verbose_name='Premium')),
                ('priority_score', models.IntegerField(db_index=True, default=0, verbose_name='Score prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='properties.amenitycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades',
                'ordering': ['-priority_score', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenity_links', to='properties.amenity', verbose_name='Amenidad')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenity_links', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Amenidad de propiedad',
                'verbose_name_plural': 'Amenidades de propiedades',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', through='properties.PropertyAmenity', to='properties.amenity', verbose_name='Amenidades (catálogo)'),
        ),
        migrations.CreateModel(
            name='AmenityAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_name', models.CharField(max_length=120, verbose_name='Alias')),
                ('alias_slug', models.SlugField(max_length=140, verbose_name='Alias slug')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='properties.amenity', verbose_name='Amenidad')),
            ],
            options={
                'verbose_name': 'Alias de amenidad',
                'verbose_name_plural': 'Aliases de amenidades',
                'indexes': [models.Index(fields=['alias_slug'], name='properties__alias_s_48e030_idx')],
                'constraints': [models.UniqueConstraint(fields=('amenity', 'alias_slug'), name='amenity_alias_unique_per_amenity'), models.UniqueConstraint(fields=('alias_slug',), name='amenity_alias_slug_unique_global')],
            },
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['slug'], name='properties__slug_132d90_idx'),
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['display_name'], name='properties__display_78571a_idx'),
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['is_active', 'priority_score'], name='properties__is_acti_9da16a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['amenity'], name='properties__amenity_3de72a_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('property', 'amenity'), name='property_amenity_unique'),
        ),
    ]
