# Generated by Django 5.2.12 on 2026-05-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_property_type_amenitycategory_amenity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(default='bi-house', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(default='bi-tools', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInteriorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.interiorfeature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='interior_features',
            field=models.ManyToManyField(blank=True, related_name='properties', through='properties.PropertyInteriorFeature', to='properties.interiorfeature', verbose_name='Distribución interior (catálogo)'),
        ),
        migrations.CreateModel(
            name='PropertyServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.servicefeature')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='service_features',
            field=models.ManyToManyField(blank=True, related_name='properties', through='properties.PropertyServiceFeature', to='properties.servicefeature', verbose_name='Servicios disponibles (catálogo)'),
        ),
        migrations.AddConstraint(
            model_name='propertyinteriorfeature',
            constraint=models.UniqueConstraint(fields=('property', 'feature'), name='property_interior_feature_unique'),
        ),
        migrations.AddConstraint(
            model_name='propertyservicefeature',
            constraint=models.UniqueConstraint(fields=('property', 'feature'), name='property_service_feature_unique'),
        ),
    ]
