# Generated by Django 5.2.12 on 2026-05-07 21:31

from django.db import migrations, models
from django.db.models import Count, Q


def dedupe_main_images(apps, schema_editor):
    PropertyImage = apps.get_model('properties', 'PropertyImage')
    dup_qs = (
        PropertyImage.objects.filter(is_main=True)
        .values('property_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for row in dup_qs:
        pid = row['property_id']
        qs = PropertyImage.objects.filter(property_id=pid, is_main=True).order_by('order', 'id')
        first = qs.first()
        if first:
            qs.exclude(pk=first.pk).update(is_main=False)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_migrate_area_to_construction_and_remove_area'),
    ]

    operations = [
        migrations.RunPython(dedupe_main_images, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['construction_area'], name='prop_construction_area_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(
                condition=Q(('is_main', True)),
                fields=('property',),
                name='uniq_property_one_main_image',
            ),
        ),
    ]
