# Generated by Django 5.2.12 on 2026-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_nosotros_manifest_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_a_desc',
            field=models.CharField(default='De principio a fin (y más allá).', max_length=320),
        ),
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_a_meaning',
            field=models.CharField(default='Acompañamiento', max_length=140),
        ),
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_l_desc',
            field=models.CharField(default='Tu patrimonio es nuestra prioridad absoluta.', max_length=320),
        ),
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_l_meaning',
            field=models.CharField(default='Lealtad', max_length=140),
        ),
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_o_desc',
            field=models.CharField(default='Procesos claros que aceleran cierres.', max_length=220),
        ),
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_t2_desc',
            field=models.CharField(default='No mostramos propiedades, construimos decisiones.', max_length=220),
        ),
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_t2_meaning',
            field=models.CharField(default='Trabajo con estrategia', max_length=140),
        ),
        migrations.AlterField(
            model_name='nosotroscontent',
            name='manifest_t_desc',
            field=models.CharField(default='Verdad completa, sin letras chiquitas.', max_length=220),
        ),
    ]
