# Generated by Django 5.2.12 on 2026-05-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_align_nosotros_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_eyebrow', models.CharField(default='Quiénes somos', max_length=80)),
                ('about_title', models.CharField(default='Total Living: Estrategia Real detrás de cada Propiedad', max_length=220)),
                ('about_paragraph_1', models.TextField(default='En Total Living no solo mostramos casas; diseñamos la ruta para que logres tu próxima gran inversión con absoluta certeza.')),
                ('about_paragraph_2', models.TextField(default='Tu tranquilidad es nuestro mejor cierre.')),
                ('about_cta_text', models.CharField(default='Conócenos', max_length=60)),
                ('about_cta_url', models.CharField(default='/contact/', max_length=240)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Imagen sección Quiénes somos')),
                ('why_title', models.CharField(default='¿Por qué elegir Total Living?', max_length=140)),
                ('why_subtitle', models.CharField(default='Trabajamos cada operación con enfoque humano, estrategia inmobiliaria y resultados medibles.', max_length=260)),
                ('why_1_icon', models.CharField(default='bi-shield-lock', max_length=40)),
                ('why_1_title', models.CharField(default='Seguridad Legal y Patrimonial', max_length=140)),
                ('why_1_text', models.CharField(default='Tu tranquilidad es nuestra prioridad absoluta.', max_length=220)),
                ('why_1_bullet_1', models.CharField(default='Validación documental y notarial.', max_length=160)),
                ('why_1_bullet_2', models.CharField(default='Contratos blindados y personalizados.', max_length=160)),
                ('why_1_bullet_3', models.CharField(default='Filtro de prospectos y procesos claros.', max_length=160)),
                ('why_1_bullet_4', models.CharField(default='Gestión de pagos segura y transparente.', max_length=160)),
                ('why_2_icon', models.CharField(default='bi-megaphone', max_length=40)),
                ('why_2_title', models.CharField(default='Marketing Premium', max_length=140)),
                ('why_2_text', models.CharField(default='Hacemos que tu propiedad destaque del resto.', max_length=220)),
                ('why_2_bullet_1', models.CharField(default='Fotografía y video de alta calidad.', max_length=160)),
                ('why_2_bullet_2', models.CharField(default='Publicidad segmentada en Meta.', max_length=160)),
                ('why_2_bullet_3', models.CharField(default='Posicionamiento en portales premium.', max_length=160)),
                ('why_2_bullet_4', models.CharField(default='Recorridos virtuales para filtrar visitas.', max_length=160)),
                ('why_3_icon', models.CharField(default='bi-bar-chart-line', max_length=40)),
                ('why_3_title', models.CharField(default='Inteligencia de Mercado', max_length=140)),
                ('why_3_text', models.CharField(default='Vendemos al precio justo, sin perder tiempo.', max_length=220)),
                ('why_3_bullet_1', models.CharField(default='Análisis comparativo de mercado.', max_length=160)),
                ('why_3_bullet_2', models.CharField(default='Reportes de tracción comercial.', max_length=160)),
                ('why_3_bullet_3', models.CharField(default='Estrategia de precio basada en datos.', max_length=160)),
                ('why_3_bullet_4', models.CharField(default='Acompañamiento para inversión y preventa.', max_length=160)),
                ('why_4_icon', models.CharField(default='bi-patch-check-fill', max_length=40)),
                ('why_4_title', models.CharField(default='Negociación y Cierre', max_length=140)),
                ('why_4_text', models.CharField(default='Expertos en obtener las mejores condiciones para ti.', max_length=220)),
                ('why_4_bullet_1', models.CharField(default='Cierre acelerado de operaciones.', max_length=160)),
                ('why_4_bullet_2', models.CharField(default='Mediación profesional entre partes.', max_length=160)),
                ('why_4_bullet_3', models.CharField(default='Gestión de créditos y viabilidad.', max_length=160)),
                ('why_4_bullet_4', models.CharField(default='Acompañamiento total hasta firma.', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
