# Generated by Django 5.2.12 on 2026-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='service_1_b1',
            field=models.CharField(default='Estrategia a la medida.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_1_b2',
            field=models.CharField(default='Acompañamiento comercial y documental.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_1_b3',
            field=models.CharField(default='Seguimiento puntual hasta el cierre.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_1_icon',
            field=models.CharField(default='bi-chat-square-text', max_length=40),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_1_text',
            field=models.CharField(default='Te acompañamos para comprar, vender o rentar con estrategia clara y atención cercana.', max_length=220),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_1_title',
            field=models.CharField(default='Asesoría personalizada', max_length=120),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_2_b1',
            field=models.CharField(default='Valoración estratégica.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_2_b2',
            field=models.CharField(default='Lectura de oferta y demanda.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_2_b3',
            field=models.CharField(default='Recomendaciones para vender mejor.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_2_icon',
            field=models.CharField(default='bi-bar-chart-line', max_length=40),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_2_text',
            field=models.CharField(default='Analizamos tu propiedad y su zona para definir el mejor posicionamiento comercial.', max_length=220),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_2_title',
            field=models.CharField(default='Análisis de mercado', max_length=120),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_3_b1',
            field=models.CharField(default='Promoción profesional.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_3_b2',
            field=models.CharField(default='Filtrado de prospectos y visitas.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_3_b3',
            field=models.CharField(default='Cierre guiado en cada etapa.', max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_3_icon',
            field=models.CharField(default='bi-house-heart', max_length=40),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_3_text',
            field=models.CharField(default='Gestionamos operaciones inmobiliarias con orden, visibilidad y enfoque en resultados.', max_length=220),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='service_3_title',
            field=models.CharField(default='Compra, venta y renta', max_length=120),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='services_subtitle',
            field=models.CharField(default='Soluciones inmobiliarias diseñadas para acompañarte con estrategia, claridad y resultados reales.', max_length=220),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='services_title',
            field=models.CharField(default='Nuestros servicios', max_length=120),
        ),
    ]
