# Generated by Django 4.2.7 on 2026-05-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_organigrammember_remove_pillars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organigrammember',
            name='slug',
            field=models.SlugField(help_text='URL pública: /nosotros/equipo/&lt;slug&gt;/ — solo letras minúsculas, números y guiones.', max_length=120, unique=True),
        ),
    ]
